- name: Install Bind9 DNS Server
  apt: name="{{ packages }}" state=present
  vars:
     packages:
     - bind9
     - bind9utils

- name: Start and Enable Bind9 DNS Server
  service: name=bind9 enabled=yes state=started

- name: Generate Bind9 configuration file
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options
  notify: reload bind9
