- name: Import PPA of DNSCrypt Proxy2 into system
  apt_repository: repo="ppa:shevchuk/dnscrypt-proxy"

- name: Install DNSCrypt-proxy
  apt: name=dnscrypt-proxy state=present

- name: Start and Enable DNSCrypt-proxy
  service: name=dnscrypt-proxy enabled=yes state=started
